import math

# =============== DEFAULT SETTINGS OF PROGRAM =================================
# SCREEN
RES = WIDTH, HEIGHT = 1200, 700
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
# FPS
FPS = 0

# NAME OF PROGRAM
NAME_PROG = 'Курсова з ООП'

# PLAYER
PLAYER_POS = 1.5, 5
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_ROT_SPEED = 0.003
PLAYER_MAX_ANGLE_X = 300  # in pixels
PLAYER_SIZE = 100

# RAY CAST
FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20
SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS

# TEXTURES
TEXTURE_SIZE = 512
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2

# MAP
SIZE_BLOCK = 100
MINI_MAP_SIZE_BLOCK = 20
MAP_PATH = "C:\\Users\\Oleg\\Desktop\\kursova\\resources\\map.txt"

# MOUSE
MOUSE_SENSITIVITY = 0.0003
MOUSE_MAX_REL = 40
MOUSE_BORDER_LEFT = 100
MOUSE_BORDER_RIGHT = WIDTH - MOUSE_BORDER_LEFT
MOUSE_BORDER_UPPER = 200
MOUSE_BORDER_LOWER = HEIGHT - MOUSE_BORDER_UPPER

# ==============================================================================


# COLORS
WHITE = (255, 255, 255)
BLACK = (20, 20, 20)
RED = (220, 0, 0)
GREEN = (0, 220, 0)
BLUE = (0, 0, 220)
SKY = (0, 186, 255)
EARTH = (0, 80, 0)
DARKGRAY = (120, 120, 120)
FLOOR_COLOR = (30, 30, 30)
